@@ -2,7 +2,7 @@
 
 /**
  * @file
- * Base module for star wars.
+ * Base module for New hope.
  */
 
 declare(strict_types=1);
@@ -12,7 +12,7 @@
 /**
  * Implements hook_mail_alter().
  */
-function sw_core_mail_alter(array &$message): void {
+function the_force_core_mail_alter(array &$message): void {
   // Allow to stop any mail send out through settings. Note if email
   // functionality needs to be tested, this code should be removed and
   // replaced with a dev mail system.
